name: Init New Service
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
        default: 'service type'
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'service name'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      id: modify_yaml
      run: |
        #!/bin/bash
        RUNTIME=${{ github.event.inputs.runtime }}
        TARGET_REPO=${{ github.event.inputs.target_repo }}
        CONFIG_FILE="repo/.github/workflows/config.yml"
        
        # Define the runtime comments and their corresponding runtimes
        sed -i "/#${RUNTIME}/a\            - runtime: ${RUNTIME}\n              target_repo: ${TARGET_REPO}" $CONFIG_FILE

    - name: Commit and push changes
      run: |
        cd repo
        git config --global user.name "Initail New Service [bot]"
        git config --global user.email "github-action[bot]"
        git add .github/workflows/config.yml
        git commit -m "Add runtime: ${{ github.event.inputs.runtime }} and target_repo: ${{ github.event.inputs.target_repo }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
