name: Add Runtime and Target Repo

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
        default: 'batch'
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      run: |
        cd repo/.github/workflows/
        runtime=${{ github.event.inputs.runtime }}
        target_repo=${{ github.event.inputs.target_repo }}

        # Use sed for debugging
        sed -i "/^- runtime: ${runtime}/a\            - runtime: ${runtime}\n              target_repo: ${target_repo}" config.yml
