on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      run: |
        cd repo/.github/workflows/
        runtime=${{ github.event.inputs.runtime }}
        target_repo=${{ github.event.inputs.target_repo }}
        text_line_1="  - runtime: ${runtime}"
        text_line_2="    target_repo: ${target_repo}"

        # Find the template section using grep
        template_section=$(grep -E "^# (.*)_template$" config.yml)

        # Add lines only if a template section is found
        if [[ ! -z "$template_section" ]]; then
          # Add new lines after the template section header using sed
          sed i "/$template_section/a \  $text_line_1" config.yml
          sed i "/$template_section/a \  $text_line_2" config.yml
        else
          echo "Error: Could not find template section in config.yml"
        fi
