name: Init New Service
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      id: modify_yaml
      run: |
        #!/bin/bash
        RUNTIME=${{ github.event.inputs.runtime }}
        TARGET_REPO=${{ github.event.inputs.target_repo }}
        CONFIG_FILE="repo/.github/workflows/config.yml"
        
        # Append new runtime and target_repo to the config.yml
        yq eval ".jobs.publish-template.strategy.matrix.include += [{\"runtime\": \"${RUNTIME}\", \"target_repo\": \"${TARGET_REPO}\"}]" -i $CONFIG_FILE

        # Reorganize matrix entries by runtime
        yq eval '
          .jobs.publish-template.strategy.matrix.include |=
            [
              .[] | select(.runtime == "java")[],
              .[] | select(.runtime == "node")[],
              .[] | select(.runtime == "batch")[],
              .[] | select(.runtime == "webhosting")[],
              .[] | select(.runtime == "maven-shared-libs")[],
              .[] | select(.runtime == "npm-shared-libs")[]
            ]
        ' -i $CONFIG_FILE

        cat $CONFIG_FILE
