name: Init New Service
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      id: modify_yaml
      run: |
        #!/bin/bash
        RUNTIME=${{ github.event.inputs.runtime }}
        TARGET_REPO=${{ github.event.inputs.target_repo }}
        CONFIG_FILE="repo/.github/workflows/config.yml"
        
        # Define the runtime comments and their corresponding runtimes
        sed -i "/#${RUNTIME}/a\            - runtime: ${RUNTIME}\n              target_repo: ${TARGET_REPO}" $CONFIG_FILE
        echo '-------------'
        echo '-------------'
        echo '-------------'
        cat $CONFIG_FILE
