name: Add Runtime and Target Repo

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
        default: 'batch'
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      run: |
        cd repo/.github/workflows/
        runtime=${{ github.event.inputs.runtime }}
        target_repo=${{ github.event.inputs.target_repo }}

        # หา index ของกลุ่ม runtime ที่ต้องการเพิ่ม
        awk -v runtime="$runtime" -v target_repo="$target_repo" '
          /- runtime: / && $3 == runtime {
            print $0
            print "            - runtime: " runtime
            print "              target_repo: " target_repo
            next
          }
          { print $0 }
        ' config.yml > temp.yml && mv temp.yml config.yml

    - name: Commit and push changes
      run: |
        cd repo
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/workflows/config.yml
        git commit -m "Add runtime and target_repo: ${{ github.event.inputs.runtime }}, ${{ github.event.inputs.target_repo }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
