name: Add Workflow New Service
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Ex.. java node batch'
        required: true
        default: 'java'
      target_repo:
        description: 'Repository name'
        required: true
        default: 'mpay-modernization-xxxxx'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{secrets.ORG_PUSH_PULL_REPO}}
        repository: ais-pci-spdg/mpay-modernization-devops
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      id: modify_yaml
      run: |
        #!/bin/bash
        RUNTIME=${{ github.event.inputs.runtime }}
        TARGET_REPO=${{ github.event.inputs.target_repo }}
        CONFIG_FILE="repo/.github/workflows/workflow-publisher.yaml"
        CONFIG_PATH="repo/config.yaml"

        # Append new runtime and target_repo to the workflow-publisher.yaml
        yq eval ".jobs.publish-template.strategy.matrix.include += [{\"runtime\": \"${RUNTIME}\", \"target_repo\": \"${TARGET_REPO}\"}]" -i $CONFIG_FILE

        # Process config.yaml
        # 1. Insert additional lines after the #${RUNTIME}_template line
        awk -v runtime="$RUNTIME" '
          /#'"${RUNTIME}"'_template/ {
            print
            # Print the lines from config.yaml matching the pattern
            system("grep -A1 '\''runtime: " runtime "'\'' " CONFIG_PATH " | tail -2")
            next
          }
          { print }
        ' config.yaml > tmp.yaml && mv tmp.yaml config.yaml

        # 2. Remove lines related to target_repo
        awk -v repo="$TARGET_REPO" '
          $0 ~ repo { skip=1 }
          skip && /^runtime:/ { skip=0 }
          !skip { print }
        ' config.yaml > tmp.yaml && mv tmp.yaml config.yaml

        # Display the modified config.yaml for verification
        cat config.yaml
