name: init

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Install yq
      run: |
        pip install yq

    - name: Modify YAML file
      id: modify_yaml
      run: |
        RUNTIME=${{ github.event.inputs.runtime }}
        TARGET_REPO=${{ github.event.inputs.target_repo }}
        CONFIG_FILE="repo/.github/workflows/config.yml"

        # Read the existing matrix include section and add new entry
        yq eval-all --inplace 'select(fileIndex == 0) * {"jobs": {"publish-template": {"strategy": {"matrix": {"include": (select(fileIndex == 0).jobs.publish-template.strategy.matrix.include + [{"runtime": env.RUNTIME, "target_repo": env.TARGET_REPO}] | sort_by(.runtime))}}}}}' $CONFIG_FILE

    - name: Display YAML file
      run: |
        CONFIG_FILE="repo/.github/workflows/config.yml"
        cat $CONFIG_FILE
