name: Set Repository Configuration

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'The name of the repository to add configuration to'
        required: true
        default: ''

jobs:
  set-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup gh cli
        run: |
          sudo apt update
          sudo apt install -y curl jq
          curl -fsSL https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_linux_amd64.deb -o ghcli.deb
          sudo dpkg -i ghcli.deb
          gh --version

      - name: Debug Info
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository Name: ${{ github.event.repository.name }}"

      - name: Set Repository Configuration
        env:
          GH_TOKEN: ${{ secrets.test }}  # Token in repo `test`
          CONFIG_AAA: ${{ secrets.AAA }}
          CONFIG_BBB: ${{ secrets.BBB }}
        run: |
          TARGET_REPO="mpay-modernization-security-test"
          CONFIGS=("CONFIG_AAA" "CONFIG_BBB")
          for CONFIG_NAME in "${CONFIGS[@]}"; do
            CONFIG_VALUE=$(eval echo \$$CONFIG_NAME)
            echo "Adding configuration ${CONFIG_NAME#CONFIG_} to $TARGET_REPO"
            echo $CONFIG_VALUE | gh secret set ${CONFIG_NAME#CONFIG_} -b - -R $TARGET_REPO
          done
