name: Init New Service
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
        default: 'java'
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      id: modify_yaml
      run: |
        #!/bin/bash
        RUNTIME=${{ github.event.inputs.runtime }}
        TARGET_REPO=${{ github.event.inputs.target_repo }}
        CONFIG_FILE="repo/.github/workflows/config.yml"
        
        # Define the runtime comments and their corresponding runtimes
        declare -A comments
        comments["#java"]="java"
        comments["#node"]="node"
        comments["#batch"]="batch"

        # Read the file and insert the new entry after the corresponding comment
        awk -v runtime="$RUNTIME" -v target_repo="$TARGET_REPO" '
        BEGIN {
          insert = 0
        }
        {
          print
          if ($0 == "#"runtime) {
            insert = 1
          } else if (insert && $0 ~ /^ *- runtime:/) {
            print "  - runtime: " runtime
            print "    target_repo: " target_repo
            insert = 0
          }
        }
        ' $CONFIG_FILE > temp.yml
        
    - name: Commit and push changes
      run: |
        cd repo
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/workflows/temp.yml
        git commit -m "Add runtime and target_repo: ${{ github.event.inputs.runtime }}, ${{ github.event.inputs.target_repo }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
