name: Add Runtime and Target Repo

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
        default: 'xxx'
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'xxx'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Setup yq
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install yq

    - name: Modify YAML file
      run: |
        cd repo/.github/workflows/
        # หา index ของกลุ่ม runtime ที่ต้องการเพิ่ม
        index=$(awk '/- runtime: '"${{ github.event.inputs.runtime }}"'/{print NR; exit}' config.yml)
        # ถ้าเจอ runtime ที่ตรงกันให้เพิ่ม entry ใหม่หลังบรรทัดนั้น
        if [ -n "$index" ]; then
          sed -i "${index}a\ \ \ \ \ \ \ \ - runtime: ${GITHUB_EVENT_INPUTS_RUNTIME}\n \ \ \ \ \ \ \ \ \ target_repo: ${GITHUB_EVENT_INPUTS_TARGET_REPO}" config.yml
        else
          echo "Runtime not found!"
          exit 1
        fi

    - name: Commit and push changes
      run: |
        cd repo
        git config --global user.name "[bot]"
        git config --global user.email "[bot]"
        git add .github/workflows/config.yml
        git commit -m "Add runtime and target_repo: ${{ github.event.inputs.runtime }}, ${{ github.event.inputs.target_repo }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
