name: Init New Service
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Modify YAML file
      id: modify_yaml
      run: |
        #!/bin/bash
        RUNTIME=${{ github.event.inputs.runtime }}
        TARGET_REPO=${{ github.event.inputs.target_repo }}
        CONFIG_FILE="repo/.github/workflows/config.yml"

        # Append new runtime and target_repo to the config.yml
        yq eval ".jobs.publish-template.strategy.matrix.include += [{\"runtime\": \"${RUNTIME}\", \"target_repo\": \"${TARGET_REPO}\"}]" -i $CONFIG_FILE

        # Reorganize matrix entries by runtime
        TEMP_FILE=$(mktemp)
        
        # Extract and reorganize each runtime category
        {
          echo "#java"
          yq eval '.jobs.publish-template.strategy.matrix.include[] | select(.runtime == "java")' $CONFIG_FILE | yq eval '.[]' - || true

          echo "#node"
          yq eval '.jobs.publish-template.strategy.matrix.include[] | select(.runtime == "node")' $CONFIG_FILE | yq eval '.[]' - || true

          echo "#batch"
          yq eval '.jobs.publish-template.strategy.matrix.include[] | select(.runtime == "batch")' $CONFIG_FILE | yq eval '.[]' - || true

          echo "#webhosting"
          yq eval '.jobs.publish-template.strategy.matrix.include[] | select(.runtime == "webhosting")' $CONFIG_FILE | yq eval '.[]' - || true

          echo "#maven-shared-libs"
          yq eval '.jobs.publish-template.strategy.matrix.include[] | select(.runtime == "maven-shared-libs")' $CONFIG_FILE | yq eval '.[]' - || true

          echo "#npm-shared-libs"
          yq eval '.jobs.publish-template.strategy.matrix.include[] | select(.runtime == "npm-shared-libs")' $CONFIG_FILE | yq eval '.[]' - || true
        } > $TEMP_FILE

        # Replace the old config file with the reorganized one
        mv $TEMP_FILE $CONFIG_FILE

        # Print the modified config.yml for verification
        cat $CONFIG_FILE
