name: Set Repository Secrets

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'The name of the repository to add secrets to'
        required: true
        default: ''

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup gh cli
        run: |
          sudo apt update
          sudo apt install -y curl jq
          curl -fsSL https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_linux_amd64.deb -o ghcli.deb
          sudo dpkg -i ghcli.deb
          gh --version

      - name: Debug Info
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository Name: ${{ github.event.repository.name }}"

      - name: Set Repository Secrets
        env:
          GH_TOKEN: ${{ secrets.test }}
        run: |
          REPO_NAME=${{ github.repository }}
          TARGET_REPO="ais-pci-spdg/mpay-modernization-security-test"
          SECRETS=("AAA" "BBB")
          for SECRET in "${SECRETS[@]}"; do
            echo "Adding secret ${SECRET} to $TARGET_REPO"
            SECRET_VALUE="${{ secrets[SECRET] }}"
            gh secret set ${SECRET} -b "$SECRET_VALUE" -R $TARGET_REPO
          done
