name: Add Runtime and Target Repo

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Specify the runtime'
        required: true
        default: 'batch'
      target_repo:
        description: 'Specify the target repository'
        required: true
        default: 'mpay-modernization-batch-newrepo'

jobs:
  add-runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: jatunon-91518/config
        path: repo
        fetch-depth: 0

    - name: Debug: Show initial content of config.yml
      run: |
        cd repo/.github/workflows/
        echo "Initial content of config.yml:"
        cat config.yml

    - name: Modify YAML file
      run: |
        cd repo/.github/workflows/
        runtime=${{ github.event.inputs.runtime }}
        target_repo=${{ github.event.inputs.target_repo }}

        # Use sed for debugging
        sed -i "/^- runtime: ${runtime}/a\            - runtime: ${runtime}\n              target_repo: ${target_repo}" config.yml

    - name: Debug: Show modified content of config.yml
      run: |
        cd repo/.github/workflows/
        echo "Modified content of config.yml:"
        cat config.yml

    - name: Commit and push changes
      run: |
        cd repo
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/workflows/config.yml
        git status
        git commit -m "Add runtime and target_repo: ${{ github.event.inputs.runtime }}, ${{ github.event.inputs.target_repo }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
